version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    env_file: .env
    ports:
      - 5432:5432
